baseURL: http://example.org/
languageCode: en-us
title: Maxi´s Blog
theme: leo

permalinks:
  posts: /:year/:month/:day/:title/

params:
  description: Hey! We are Maxi and Alex, two developers from Germany.
